---
config:
  layout: dagre
---
flowchart TD
 subgraph s0["Resume Tailoring Orchestra"]
        START --> E1["Job Positions Found"]
        J1["Best Practices + Master Resume + Company Culture"]
        J3["Master Resume + Company Culture + Downloaded Job Descriptions"]
        s1
        J3 --> SO2["JD Matching Orchestra"]
        SO2 --> OUT4["Selected Parsed JDs + Match and Skills Gap Analysis"]
        s3

        SO4["Polishing Orchestra"]
        SO4 --> SO5

        SO5["Ideal Length Fitting Orchestra"]
        SO5 --> OUT1(["Release Version"])
        STOP

        START@{ shape: start}
        E1@{ shape: event}
        J1@{ shape: junction}
        J3@{ shape: junction}
        SO2@{ shape: procs}
        OUT4@{ shape: docs}
        SO4@{ shape: procs}
        SO5@{ shape: procs}
        STOP@{ shape: stop}

        s1:::INPUT_BLOCK
        SO2:::SUBORCHESTRA
        OUT4:::OUTPUT
        s3:::ORCHESTRA
        SO4:::SUBORCHESTRA
        SO5:::SUBORCHESTRA
        
        style J1 stroke #000
        style J3 stroke #000
 end
  E1 --> MA1 & IN0

 subgraph s1["Input"]
        MA1["Document Fetcher (Fetch Raw Job Descriptions)"]
        IN0["Input Reader"] -- Read--> IN1 & IN2 & IN3

        %% Input Documents
        IN1["Resume Best Practices Guidelines"]
        IN2["Master Resume"]
        IN3["Company Culture Report"]
        MA1 --> OUT3["Raw Job Descriptions"]

        %% Shape definitions
        MA1@{ shape: procs}
        IN0@{ shape: proc}
        IN1@{ shape: doc}
        IN2@{ shape: doc}
        IN3@{ shape: doc}
        OUT3@{ shape: docs}
        
        %% Class assignments
        MA1:::AGENT
        IN0:::INPUT
        IN1:::INPUT
        IN2:::INPUT
        IN3:::INPUT
        OUT3:::OUTPUT
  end
  IN1 --> J1
  IN2 --> J1 & J3 & J9
  IN3 --> J1 & J3
  OUT3 --> J3
  J1 --> J7

 subgraph s3["Draft writing Orchestra"]
        J9 --> J4 & J5
        J4 --> A4["Fact Checker"]
        J7 --> A3["Draft Writer"]
        A3 --> J4
        D2 -- Yes --> H["Revised Draft Writer"]
        A4 --> D2{"Has False Facts?"}
        H --> J5
        J5 --> A4
        
        %% Shape definitions
        J9@{ shape: junction}
        J4@{ shape: junction}
        A4@{ shape: procs}
        J7@{ shape: junction}
        A3@{ shape: doc}
        H@{ shape: doc}
        J5@{ shape: junction}
        
        %% Class assignments
        A4:::AGENT
        A3:::OUTPUT
        D2:::DECISION
        H:::OUTPUT
        
        %% Styles
        style J9 stroke #000
        style J4 stroke #000
        style J7 stroke #000
        style J5 stroke #000
  end
    D2 -- No --> SO4
    OUT4 --> J7
    OUT1 --> STOP

    classDef ORCHESTRA stroke-width:2px, stroke-dasharray:none, stroke:#D50000, fill:transparent, color:#D50000
    classDef SUBORCHESTRA stroke-width:2px, stroke-dasharray:none, stroke:#2962FF, fill:FFE0B2, color:#FFFFFF
    classDef INPUT_BLOCK stroke-width:2px, stroke-dasharray:none, stroke:#00C853, fill:transparent, color:#00C853
    classDef INPUT stroke-width:2px, stroke-dasharray:none, fill:#e6ffe6, color:#000000
    classDef EVENT stroke-width:2px, stroke-dasharray:none, fill:#BBDEFB, color:#000000
    classDef RESEARCH stroke-width:2px, stroke-dasharray:none, fill:#FFF9C4, color:#000000
    classDef AGENT stroke-width:2px, stroke-dasharray:none, fill:#FFE0B2, color:#000000
    classDef DECISION stroke-width:2px, stroke-dasharray:none, fill:#E1BEE7,stroke:#D50000, color:#000000
    classDef RELEASE_CANDIDATE stroke-width:2px, stroke-dasharray:none, fill:#FFF9C4, stroke:#D50000, color:#000000
    classDef OUTPUT stroke-width:2px, stroke-dasharray:none, fill:#C8E6C9, color:#000000
